"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Student_1 = require("./src/classes/Student");
var studentOne = new Student_1.default('12345', 'João', new Date(2000, 1, 1));
console.log(studentOne);
studentOne.examsGrades = [5, 6, 7, 8];
studentOne.worksGrades = [10, 10];
var st1SumGrades = studentOne.calculateSumGrades();
var st1AverageGrade = studentOne.calculateAverageGrade();
console.log("A m\u00E9dia de ".concat(studentOne.name, " \u00E9 ").concat(st1AverageGrade, " e sua soma de notas \u00E9 ").concat(st1SumGrades));
var studentTwo = new Student_1.default('54321', 'Maria', new Date(2000, 2, 1));
console.log(studentTwo);
studentTwo.examsGrades = [10, 9, 8, 7];
studentTwo.worksGrades = [10, 10];
var st2SumGrades = studentTwo.calculateSumGrades();
var st2AverageGrade = studentTwo.calculateAverageGrade();
console.log("Notas de provas de ".concat(studentTwo.name, ": ").concat(studentTwo.examsGrades));
console.log("Notas de trabalhos de ".concat(studentTwo.name, ": ").concat(studentTwo.worksGrades));
console.log("A m\u00E9dia de ".concat(studentTwo.name, " \u00E9 ").concat(st2AverageGrade, " e sua soma de notas \u00E9 ").concat(st2SumGrades));
